In [1]:
import pandas as pd

C:\Users\Alumno\AppData\Local\Temp\ipykernel_1464\2035458946.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
net = pd.read_csv('netflix_titles.csv')

In [3]:
net.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [4]:
net.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [5]:
#no se deben eliminar los registros nulos por que asi desaparecer todos los registros

In [6]:
net.sample()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8303,s8304,Movie,The Five Venoms,Cheh Chang,"Philip Kwok, Chien Sun, Sheng Chiang, Feng Lu,...",Hong Kong,"July 31, 2018",1978,R,97 min,"Action & Adventure, Cult Movies, International...",A dying kung fu master sends his last student ...

In [7]:
net.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [8]:
net_peliculas = net.loc[net['type'] == 'Movie']
net_series = net.loc[net['type'] == 'TV Show']

In [9]:
peliculas= net[net['type']=='movie']

In [10]:
net['type'].unique

<bound method Series.unique of 0         Movie
1       TV Show
2       TV Show
3       TV Show
4       TV Show
         ...
8802      Movie
8803    TV Show
8804      Movie
8805      Movie
8806      Movie
Name: type, Length: 8807, dtype: object>

In [11]:
series= net[net['type']=='TV Show']

In [12]:
net['type'].unique

<bound method Series.unique of 0         Movie
1       TV Show
2       TV Show
3       TV Show
4       TV Show
         ...
8802      Movie
8803    TV Show
8804      Movie
8805      Movie
8806      Movie
Name: type, Length: 8807, dtype: object>

In [13]:
series.sample()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
848,s849,TV Show,Master of None,NaN,"Aziz Ansari, Noël Wells, Eric Wareheim, Lena W...",United States,"May 23, 2021",2021,TV-MA,3 Seasons,"TV Comedies, TV Dramas",Dev tries to jump-start his acting career and ...

In [14]:
peliculas['date_added']=peliculas['date_added'].str.strip()

In [15]:
peliculas['date_added'] = pd.to_datetime(peliculas['date_added'])

In [16]:
peliculas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       0 non-null      object
 1   type          0 non-null      object
 2   title         0 non-null      object
 3   director      0 non-null      object
 4   cast          0 non-null      object
 5   country       0 non-null      object
 6   date_added    0 non-null      datetime64[ns]
 7   release_year  0 non-null      int64
 8   rating        0 non-null      object
 9   duration      0 non-null      object
 10  listed_in     0 non-null      object
 11  description   0 non-null      object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 0.0+ bytes

In [17]:
series['date_added']=series['date_added'].str.strip()

C:\Users\Alumno\AppData\Local\Temp\ipykernel_1464\1426276207.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  series['date_added']=series['date_added'].str.strip()

In [18]:
series['date_added'] = pd.to_datetime(series['date_added'])

C:\Users\Alumno\AppData\Local\Temp\ipykernel_1464\2339821119.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  series['date_added'] = pd.to_datetime(series['date_added'])

In [19]:
series.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2676 entries, 1 to 8803
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       2676 non-null   object
 1   type          2676 non-null   object
 2   title         2676 non-null   object
 3   director      230 non-null    object
 4   cast          2326 non-null   object
 5   country       2285 non-null   object
 6   date_added    2666 non-null   datetime64[ns]
 7   release_year  2676 non-null   int64
 8   rating        2674 non-null   object
 9   duration      2676 non-null   object
 10  listed_in     2676 non-null   object
 11  description   2676 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 271.8+ KB

In [20]:
net_peliculas['duration'] =net_peliculas['duration'].str.replace(' min','')
net_peliculas['duration'] =net_peliculas['duration'].str.strip()
net_peliculas['duration'] =net_peliculas['duration'].astype

C:\Users\Alumno\AppData\Local\Temp\ipykernel_1464\2827544247.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  net_peliculas['duration'] =net_peliculas['duration'].str.replace(' min','')
C:\Users\Alumno\AppData\Local\Temp\ipykernel_1464\2827544247.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  net_peliculas['duration'] =net_peliculas['duration'].str.strip()
C:\Users\Alumno\AppData\Local\Temp\ipykernel_1464\2827544247.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  net_peliculas['duration'] =net_peliculas['duration'].astype

In [34]:
net_series

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
8795,s8796,TV Show,Yu-Gi-Oh! Arc-V,NaN,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada","May 1, 2018",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...
8796,s8797,TV Show,Yunus Emre,NaN,"Gökhan Atalay, Payidar Tüfekçioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

In [43]:
def filmografia(actor:str):#define funcion filmografia que recibe una cadena de texto
    result1 = net_peliculas[net_peliculas['cast'].str.contains(actor,na=False)]#filtra registros que contenga la cadena de texto ingresada
    result2 = net_series[net_series['cast'].str.contains(actor, na=False)]#filtra registros que contenga la cadena de texto ingresada
    result1 =result1[['title','release_year','type']]#sobreescribir reult1 con las columnas'title','release_year','type'
    result2 =result2[['title','release_year','type']]#sobreescribir reult2 con las columnas'title','release_year','type'
    result = pd.concat([result1,result2], axis=0).sort_values(by='release_year', ascending=True)#se
    result['type'] =result['type'].str.replace('Movie','Pelicula').replace('TV Show','Serie')
    return result.rename(columns={'title':'Título','release_year':'Año de Lanzamiento','type':'Tipo'}).reset_index(drop=True)

In [42]:
filmografia('Gael')

                     Título  Año de Lanzamiento      Tipo
0         Y Tu Mamá También                2001  Pelicula
1                     Babel                2006  Pelicula
2         Letters to Juliet                2010  Pelicula
3             Even the Rain                2010  Pelicula
4          Casa de mi Padre                2012  Pelicula
5                    Neruda                2016  Pelicula
6  The Kindergarten Teacher                2018  Pelicula
7           Sakho & Mangane                2019     Serie
8              Wasp Network                2020  Pelicula